### ISSUE TITLE
genericTagQueryList does not correctly serialize

### ISSUE THREAD

**Issue by kuiperanon** [tcheeric/nostr-java#144]
```
        String new_geohash = "2vgddg";
        List<String> geohashList = new ArrayList<String>();
        geohashList.add(new_geohash);
        genericTagQuery.setValue(geohashList);
        Filters filters = NIP01.createFilters(null, null, null, null, null, null, null, null, new GenericTagQueryList(genericTagQuery));
```

If you send this, then the sent serialized REQ string looks like this:

```
INFO: Sending serialized message: ["REQ","de3daa94-ff45-496f-b1a4-13d6ba50abe6",{"genericTagQueryList":[{"nip":1,"#g":["2vghde"]}]}]
```

When it should be more like:
```
INFO: Sending serialized message: ["REQ","de3daa94-ff45-496f-b1a4-13d6ba50abe6","#g":["2vghde"]}]}]
```

**Comment by tcheeric** [comment]
I'll take a look
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


17 Apr 2024, 04:34 by ***@***.***:

**Comment by tcheeric** [comment]
This is actually currently not supported. I will look into it.

**Comment by tcheeric** [comment]
I think you are referring to the serialiser, right? Please confirm. (deserialising is not supported)

**Comment by kuiperanon** [comment]
I meant serialize.

**Comment by tcheeric** [comment]
This made me realise a mistake in the implementation, due to a misinterpretation of the spec. 
NIP-01 defines Filters as follows: 
```
{
  "ids": <a list of event ids>,
  "authors": <a list of lowercase pubkeys, the pubkey of an event must be one of these>,
  "kinds": <a list of a kind numbers>,
  "#<single-letter (a-zA-Z)>": <a list of tag values, for #e — a list of event ids, for #p — a list of pubkeys, etc.>,
  "since": <an integer unix timestamp in seconds, events must be newer than this to pass>,
  "until": <an integer unix timestamp in seconds, events must be older than this to pass>,
  "limit": <maximum number of events relays SHOULD return in the initial query>
}
```

Filters do not accept ```GenericTagQueryLists```, as incorrectly assumed, but instead, ```GenericTagQuery```s
I have made the corrections in the Filters class, and adjusted the corresponding encoder and serializer.

More test cases are needed to ensure the current implementation is bullet-proof, but it looks promising.

I have pushed the changes in the branch ```feature/Issue_144``` and will add more test cases tomorrow.
