### ISSUE TITLE
Change maven project's structure

### ISSUE THREAD

**Issue by guilhermegps** [tcheeric/nostr-java#20]
What do you think about changing the structure of the project? Instead of have a multi-modules structure, we'd have just one module maven with many packages (to organize the code). It'll be easiest to integrate the code among the packages. Today we have a lot of problems with dependencies because maven can't have cyclic dependencies (you can read more about it [here](https://en.wikipedia.org/wiki/Acyclic_dependencies_principle)).

Something like that (without Spring, of course):
![image](https://user-images.githubusercontent.com/13434802/231007957-c469f6e3-aab8-41eb-a4ef-b72918196a00.png)

Just one pom.xml for whole project.
![image](https://user-images.githubusercontent.com/13434802/231008506-e0ea495f-1e17-4547-a9f4-8c0ab10c91f6.png)

**Comment by guilhermegps** [comment]
Or maybe all we need is just to organize better the modules

**Comment by tcheeric** [comment]
I thought about this too. 

The reason I tend to create separate modules is because this is how I conceptualise the whole thing in my mind. I break it down in smaller parts and create a module for each one.

Also, I was thinking of using some of the sub-modules in a different project.

I suggest we keep this open and revisit later? For now, I want to put the focus on creating a release.
